### ISSUE TITLE
你好，请问几个问题，谢谢

### ISSUE THREAD

**Issue by roy2651** [TMLAndroid/MiniCapAndMiniTouch#2]
1.你好，这个是投屏端还是接收端，还是两个都可以
2.这个是基于什么来做的，DLNA还会mirccast，或者是webrtc
3.我也在学习做手机投屏，如果可以方便加一个qq请教问题
4.期待着你的回复，谢谢

**Comment by TMLAndroid** [comment]
这个是基于java客户端，JSwing,主要是接收手机发来的图片的byte数据，解析成图片，手机上采用的minicap编译好的文件，通过JSwing推到手机，然后执行，进行端口转发来实现（PS：minicap本质实现是调用Android被hiden的类来实现的，网上有方法，可以用java实现）
